apiVersion: v2
name: brightmove-engage-postgres
version: 1.0.0
appVersion: stage
description: BrightMove Engage Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - engage
sources:
  - https://github.com/BrightMove/brightmove-engage.git
maintainers:
  - name: Kayla Jones
    email: kayla.jones@brightmove.com
deprecated: false
annotations:
  created: "12/18/2025"
