apiVersion: v2
name: brightmove-ats
version: 1.0.200
appVersion: 2025.14.1.1347
description: BrightMove ATS Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - ats
sources:
  - https://github.com/BrightMove/brightmove-ats.git
maintainers:
  - name: David Webb
    email: dwebb@brightmove.com
deprecated: false
annotations:
  created: "03/24/2023"
