apiVersion: v2
name: cloud-tuner
version: 1.0.17
appVersion: 2.3.1.61
description: Cloud Tuner Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/cloud-tuner.svg
keywords:
  - aws
sources:
  - https://github.com/BrightMove/cloud-tuner.git
maintainers:
  - name: David Webb
    email: dwebb@brightmove.com
deprecated: false
annotations:
  created: "09/23/2021"
