apiVersion: v2
name: brightmove-ax-legacy
version: 1.0.46
appVersion: 2025.7.3.251
description: BrightMove AX Legacy Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - ax
  - applicant
  - portal
sources:
  - https://github.com/BrightMove/brightmove-ax.git
maintainers:
  - name: David Webb
    email: dwebb@brightmove.com
deprecated: false
annotations:
  created: "04/13/2023"
