apiVersion: v2
name: brightmove-ax-legacy-postgres
version: 1.0.3
appVersion: 2025.8.0-SNAPSHOT.187
description: BrightMove AX Legacy Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - ax
  - applicant
  - portal
sources:
  - https://github.com/BrightMove/brightmove-ax.git
maintainers:
  - name: David Webb
    email: dwebb@brightmove.com
  - name: Kayla Jones
    email: kayla.jones@brightmove.com
deprecated: false
annotations:
  created: "11/18/2025"
