apiVersion: v2
name: brightmove-processes
version: 1.0.25
appVersion: 2026.1.0.52
description: BrightMove Processes Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - processes
sources:
  - https://github.com/BrightMove/brightmove-processes.git
maintainers:
  - name: Dane Woodall
    email: dwoodall@brightmove.com
deprecated: false
annotations:
  created: "05/17/2024"
