apiVersion: v2
name: brightmove-processes-postgres
version: 1.0.0
appVersion: stage
description: BrightMove Processes Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - processes
sources:
  - https://github.com/BrightMove/brightmove-processes.git
maintainers:
  - name: Dane Woodall
    email: dwoodall@brightmove.com
deprecated: false
annotations:
  created: "12/18/2025"
